---@class Rioni.LOVElyBullets.Generator
---@field bullets Rioni.LOVElyBullets.Bullet[] List of all bullets generated by this generator
---@field current_formation Rioni.LOVElyBullets.Bullet[] Bullets in the current formation
---@field args any[] Arguments for the coroutine
---@field coroutine thread Coroutine that generates the bullets
---@field system Rioni.LOVElyBullets.BulletSystem Reference to the BulletSystem
---@field wait_time number Delay before resuming the coroutine
---@field pending_formations table[] Formations pending activation
---@field current_subformation table[] Formation being built
---@field generator_timer number Time to wait for the next generation
local Generator = {}
Generator.__index = Generator

---@param args any[]
---@param coroutine thread
---@param system Rioni.LOVElyBullets.BulletSystem
function Generator.new(system, coroutine, args)
    local self = setmetatable({}, Generator)
    self.bullets = {}
    self.current_formation = {}
    self.args = args
    self.coroutine = coroutine
    self.system = nil
    self.wait_time = 0
    self.pending_formations = {}
    self.current_subformation = {}
    self.generator_timer = 0
    self.system = system
    return self
end

---Updates the generator,it will dispose itself from the system when it's done
---@param dt number Delta time
function Generator:update(dt)
    -- If you're reading this code, stop or be ready to what's coming next

    for i = #self.pending_formations, 1, -1 do
        local formation = self.pending_formations[i]
        formation.timer = formation.timer - dt
        if formation.timer <= 0 then
            for _, bullet in ipairs(formation.bullets) do
                bullet.active = true
            end
            table.remove(self.pending_formations, i)
        end
    end

    local time_left = dt
    while time_left > 0 and self.coroutine do
        if self.generator_timer > time_left then
            self.generator_timer = self.generator_timer - time_left
            time_left = 0
        else
            time_left = time_left - self.generator_timer
            self.generator_timer = 0

            while self.generator_timer <= 0 and self.coroutine do
                local status, bullet, wait_time, enable_time, wait_to_enable = coroutine.resume(self.coroutine,
                    unpack(self.args))
                if not status then
                    self:cancel()
                    return
                end

                if bullet then
                    local instance = self.system:create_bullet(bullet) ---@diagnostic disable-line:invisible
                    table.insert(self.current_subformation, instance)
                    table.insert(self.bullets, instance)
                    self.generator_timer = wait_time or 0
                else
                    -- Formation end because bullet was nil
                    if #self.current_subformation > 0 then
                        local formation = {
                            bullets = self.current_subformation,
                            timer = (enable_time and enable_time > 0) and enable_time or 0
                        }
                        if formation.timer > 0 then
                            table.insert(self.pending_formations, formation)
                        else
                            for _, b in ipairs(formation.bullets) do
                                b.active = true
                            end
                        end
                        self.current_subformation = {}
                    end

                    if wait_to_enable then
                        self.generator_timer = (enable_time or 0) + (wait_time or 0)
                    else
                        self.generator_timer = wait_time or 0
                    end
                end

                if self.generator_timer > 0 then break end

                if coroutine.status(self.coroutine) == "dead" then
                    for i = #self.pending_formations, 1, -1 do
                        local formation = self.pending_formations[i]
                        for _, b in ipairs(formation.bullets) do
                            b.active = true
                        end
                        table.remove(self.pending_formations, i)
                    end
                    self.coroutine = nil
                    break
                end
            end
        end
    end
end

---Cancels the current bullet generation.
---@param keep_bullets boolean? If true, the bullets will be kept and activated if they weren't, otherwise they will be removed.
function Generator:cancel(keep_bullets)
    self.system:_remove_generator(self) ---@diagnostic disable-line:invisible

    if keep_bullets == nil then
        keep_bullets = true
    end

    if keep_bullets then
        if (not self.coroutine) or (coroutine.status(self.coroutine) == "dead" and self.generator_timer <= 0 )then return end

        for i = #self.pending_formations, 1, -1 do
            local formation = self.pending_formations[i]
            for _, b in ipairs(formation.bullets) do
                b.active = true
            end
            table.remove(self.pending_formations, i)
        end

        for _, bullet in ipairs(self.current_subformation) do
            bullet.active = true
        end
    else
        for _, bullet in ipairs(self.bullets) do
            self.system:_remove_bullet(bullet) ---@diagnostic disable-line:invisible
        end
    end
end

return Generator